### ISSUE TITLE
PDSim GUI failed to copy/paster coordinate from excel

### ISSUE THREAD

**Issue by Wang-Zongwei** [ibell/pdsim#83]
Today I found below issue, and I hope my feedback is useful.

When I tried to input x/y coordinates in "Set Disc port coordinates", PDSim GUI failed to copy/paster coordinate from excel.
 There is no any response.  So I had to input data one by one. (see below pic)
![Set Disc port coordinates](https://github.com/ibell/pdsim/assets/112040078/b7b3bff6-3559-4476-a989-8ffc48e873a3)
)

Below information showed in main output log:

C:\pdsim-master0826\GUI\panels\scroll_panels.py:346: wxPyDeprecationWarning: Call to deprecated item. Use SetSize instead.
  self.SetSizeWH(w+40,w)
C:\pdsim-master0826\GUI\panels\scroll_panels.py:251: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  menu.AppendItem(menuitem1)
Traceback (most recent call last):
  File "C:\pdsim-master0826\GUI\panels\scroll_panels.py", line 282, in OnPaste
    self.update_from_configfile(zip(*rows))
  File "C:\pdsim-master0826\GUI\panels\scroll_panels.py", line 309, in update_from_configfile
    self.ResizeGrid(len(values[0]))
TypeError: 'zip' object is not subscriptable

**Comment by Wang-Zongwei** [comment]
I found the lastest version has already solved this issue. Thanks a lot.
