### ISSUE TITLE
PDSim GUI failed to use the vapor injection function

### ISSUE THREAD

**Issue by Wang-Zongwei** [ibell/pdsim#85]
Today I found below issue, and I hope my feedback is useful.

When I tried to use "vapor injection for scroll compressor", there's no any response when when I clicked the button "Add Injection Line". (see below pic)

![QQ截图20231013155456](https://github.com/ibell/pdsim/assets/112040078/c0364b12-5b04-4211-80e5-4dc49ac66947)

Below information showed in main output log:
Traceback (most recent call last):
  File "C:\pdsim-master\GUI\plugins\scroll_plugins.py", line 422, in OnAddInjection
    IE = InjectionElementPanel(self.scrolled_panel,self.Nterms+1)
  File "C:\pdsim-master\GUI\plugins\scroll_plugins.py", line 265, in __init__
    IPP = InjectionPortPanel(self, index = 1)
  File "C:\pdsim-master\GUI\plugins\scroll_plugins.py", line 40, in __init__
    self.AddPort.Bind(wx.EVT_BUTTON,self.Parent.OnAddPort(self))
  File "C:\pdsim-master\GUI\plugins\scroll_plugins.py", line 340, in OnAddPort
    IPP = InjectionPortPanel(self, index = len(self.ports_list)+1)
AttributeError: 'InjectionElementPanel' object has no attribute 'ports_list'

**Comment by ibell** [comment]
Hmm I haven't worked with that code in years. Can you debug yourself?

**Comment by Wang-Zongwei** [comment]
OK, I will try, thanks.
